### ISSUE TITLE
Just going to do a pull request

### ISSUE THREAD

**Issue by richteel** [bobricius/Armachat-circuitpython#2]
I was just going to make a pull request as I made several changes than make the compact version more stable and usable. I see some changes made today so I will compare and see if everything was addressed in your update.

**Fixes made following forks**
- richteel/Armachat-circuitpython
- Kayto/Armachat-circuitpython

---

- Much more stable
- Viewing messages after sending a message does not cause a crash
- Index issue fixed to prevent random crashes
- The boot.py file is setup for Compact version. Use previous version if using max version
- BTW: Save memory to flash does work if you change the file system to write mode by pressing the ALT key when booting and pressing the S key when viewing messages.

**Comment by Kayto** [comment]
Sounds good. I incorporated some changes last week that came from Peter not via github. Only just seen this latest update from Peter in the main repo. Looks the same one minus some of my working additions of ping and cpu temp etc.

Have a check over as the main additions are the radio profiles. 

Additionally, if you have anything to add on the discussions I opened on my fork then please comment. The idea was to perhaps start a wiki or at least try to document the code - frequently asked questions etc.

**Comment by richteel** [comment]
@Kayto I did not see your changes. I pulled from your repo and checked in my changes to your repo. I just made some more changes and have made the code more stable, standardized some formatting with Mu editor (check and tidy), load the frequency from config and apply it to the radio, and implemented changing radio profile on the fly. It looks much better than it did a few days ago. At least it is usable now. ;-)

**Comment by richteel** [comment]
BTW: I plan to upload my build video(s) to YouTube. I worked on it this weekend, but my video editing software, Corel VideoStudio 2022, crashed on me repeatedly. I'm going to have a go at it again later this week or over the weekend.

**Comment by Kayto** [comment]
@richteel thanks for the work on this - much appreciated.

**Comment by bobricius** [comment]
@richteel thanks you made lot of professional changes, I have try run on my board but I wan unable to solve all dependencies, can you please upload all required files?
I updated my changes, mostly only changed font format to PCF which is loaded quickly an is used default in menu and editor (maybe in editor is faster to use terminal font with scale 2)
we get back extra row on screen which can be used as status or UI help.

**Comment by richteel** [comment]
Peter,

 

I believe I uploaded everything, but I will check in about an hour. Sorry, I know the time difference creates quite the delay. I’m still at work and should be wrapping up in an hour.

 

Rich

**Comment by richteel** [comment]
I just pulled my code over and checked with my repository and did not see any missing files. I do see that I have an error in the code that I may try to fix shortly.
I thought I had an issue with my config.py file but that is fine. If you are having issues, it could be that your module is a 868.0 MHz module. The config file I checked in is set for 915.0 MHz. The code is using the frequency in the config file. Previously, it was using the ulora default of 868.0 MHz.

BTW: boot.py is setup for a Compact not a Max unit. That is something that needs to be addressed. Perhaps having it read from the config file. I may try that at some point.

**Comment by bobricius** [comment]
I get problem with PlatformDetect, then I remove this lines, I gen another error, then it was mounted in read only and it was end

**Comment by richteel** [comment]
I'm not finding PlatformDetect in my code, Kayto, or your code. Can you point me to the file that the reference is in?

Oh, just a thought, can we be on different versions of CircuitPython? I installed adafruit-circuitpython-raspberry_pi_pico-en_US-7.2.0.uf2. My lib files are from adafruit-circuitpython-bundle-7.x-mpy-20220304.zip

**Comment by richteel** [comment]
BTW: I just checked and I used the libraries that are in your repo so I suspect it is the version of CircuitPython.

I'm wondering if you are writing new code that requires the adafruit_platformdetect. I have not looked at that library and not certain if it would add value. It looks like it may be primarily for Adafruit Blinka projects. It is available at https://github.com/adafruit/Adafruit_Python_PlatformDetect and some information for installing is at https://learn.adafruit.com/circuitpython-libraries-on-micropython-using-the-raspberry-pi-pico/installing-blinka-and-libraries. I just tried a sample I found at https://docs.circuitpython.org/projects/platformdetect/en/latest/index.html, but it failed with the following error.

Traceback (most recent call last):
  File "code.py", line 16, in <module>
  File "adafruit_platformdetect/__init__.py", line 11, in <module>
ImportError: no module named 'typing'

I suspect it would need another library to run. It is late so calling it a night.

**Comment by bobricius** [comment]
sorry, sorry, I was mistaken, very similar names (richteel/rgrizzel ) I tested https://github.com/rgrizzell/Armachat-circuitpython
